r2pipe.go: do not use `q!` because of the -1 exit code
radareorg/radare2-r2pipe pull request #125
Opened 2020-12-03 07:20 UTC by XVilka

Currently if radare2 executes `q!` it returns -1 exit code
which masks the possible errors when r2pipe.go used.
Changing to `q` will ensure that exit code is 0 in case of success.

2020-12-03 07:28 UTC, davendu commented
Maybe we may need `Pipe.Close()` for `q` and `Pipe.Kill()` for `q!`? And return error when `Pipe.Close()` if `q` does not shutdown the process. Is `Pipe` going to hold the child process in its control, or only act as a pipe? If the process is holding by `Pipe` it might be necessary to it.

2020-12-03 07:46 UTC, fangxlmr commented
@davendu 

`Pipe.Kill()` is a good idea to demonstrate forced quit.

And I don't think `Pipe` will hold the child process sicne r2 is called and executed via [exec.Command](https://golang.org/pkg/os/exec/#Command), so using `q!` is enough I guess.

2020-12-03 08:47 UTC, trufae approved these changes

2020-12-03 08:48 UTC, trufae requested changes
Maybe nice to have a QuickClose() maybe to keep this fast closing times. Also..i dont see why q! should return -1. i think this is a bug that must be fixed in r2 instead of doing this workaround here.

2020-12-03 08:59 UTC, XVilka commented
I added `ForceClose()` method to run `q!` instead. Let me know if the name is fine.

2020-12-03 15:02 UTC, wargio approved these changes
ForceClose sounds exactly what `q!` does.

2020-12-11 10:48 UTC, trufae commented
Fixed in https://github.com/radareorg/radare2/pull/18019

2020-12-11 10:48 UTC, trufae approved these changes

2020-12-11 10:49 UTC, merged

2020-12-11 10:50 UTC, trufae commented
Merging for now. ill sync/fix the duplicated r2pipe.go repository issue